apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000       # Port interne du service
      targetPort: 5001 # Port sur lequel ton app écoute dans le conteneur
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mhd0/express-mongo-react-backend:1
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5001"
            - name: MONGODB_URI
              value: "mongodb://admin:password123@mongodb-service:27017/smartphoneDB?authSource=admin"
